version: '3.8'

services:
  db_pizzeria:
    image: mysql:8.0
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'mysecretpassword'
      MYSQL_DATABASE: 'BD_SISTEMA_PIZZERIA'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://root:mysecretpassword@db_pizzeria:3306/BD_SISTEMA_PIZZERIA
      - PORT=3000
    command: sh -c "npm run dev"
    depends_on:
      - db_pizzeria

